import { AlertTriangle, CheckCircle2, CircleDot, Copy, Gauge, MapPin, Route as RouteIcon } from 'lucide-react';
import type { MobilityPosition, MobilityProfile, ModuleStatus, RouteResult } from '../../types/domain';
import { formatCoordinates } from '../../lib/format';
import { formatDistance, formatRouteDuration, mobilityError, profileLabel } from '../../features/mobility/model';

export function ProfileBadge({ profile }: { profile: MobilityProfile }) { return <span className={`mobility-profile ${profile.toLowerCase()}`}><CircleDot />{profileLabel(profile)}</span>; }

export function ModuleStatusView({ module }: { module?: ModuleStatus }) {
  if (!module) return <div className="module-unavailable"><AlertTriangle /><div><strong>Mobility is not enabled for this deployment.</strong><span>Other Polaris services remain available.</span></div></div>;
  return <div className="module-status-view"><div className="module-status-main"><span className={`module-state ${module.state.toLowerCase()}`}>{module.state}</span><div><strong>Mobility</strong><span>{module.message || 'Runtime module state'}</span></div></div>{module.components && <div className="component-states">{Object.entries(module.components).map(([name, status]) => <div key={name}><span>{name}</span><strong className={status.state.toLowerCase()}>{status.state}</strong></div>)}</div>}</div>;
}

export function CoordinateFields({ label, value, onChange, selecting, onSelectMode, error }: { label: string; value: MobilityPosition; onChange: (value: MobilityPosition) => void; selecting?: boolean; onSelectMode?: () => void; error?: string }) {
  return <fieldset className="coordinate-fields"><legend>{label}</legend><label>Latitude<input type="number" step="0.000001" value={Number.isFinite(value.latitude) ? value.latitude : ''} onChange={event => onChange({ ...value, latitude: event.target.value === '' ? Number.NaN : Number(event.target.value) })} /></label><label>Longitude<input type="number" step="0.000001" value={Number.isFinite(value.longitude) ? value.longitude : ''} onChange={event => onChange({ ...value, longitude: event.target.value === '' ? Number.NaN : Number(event.target.value) })} /></label>{onSelectMode && <button type="button" className={`button secondary coordinate-pick ${selecting ? 'active' : ''}`} onClick={onSelectMode}><MapPin />{selecting ? 'Click the map…' : 'Choose on map'}</button>}{error && <small className="field-error">{error}</small>}</fieldset>;
}

export function RouteErrorCard({ error }: { error: unknown }) { const value = mobilityError(error); return <div className="route-error-card" role="alert"><AlertTriangle /><div><strong>{value.title}</strong><p>{value.message}</p>{value.requestId && <button className="copy-request" onClick={() => void navigator.clipboard?.writeText(value.requestId!)}><Copy /> Request ID: <code>{value.requestId}</code></button>}</div></div>; }

export function RouteSummary({ route, persisted = false }: { route: RouteResult; persisted?: boolean }) {
  return <div className="route-result"><div className="route-result-title"><span><RouteIcon /></span><div><small>{persisted ? 'Persisted Command Route' : 'Exploratory route'}</small><strong>{route.route_id}</strong></div></div><div className="route-metrics"><div><small>Policy</small><strong>{route.policy === 'FASTEST' ? 'Fastest time' : 'Shortest distance'}</strong></div><div><small>Distance</small><strong>{formatDistance(route.distance_meters)}</strong></div><div><small>Estimated duration</small><strong>{formatRouteDuration(route.estimated_time)}</strong></div><div><small>Waypoints</small><strong>{route.waypoints.length.toLocaleString()}</strong></div></div><details open><summary>Route metadata</summary><dl className="route-metadata"><div><dt>Road graph</dt><dd>{route.road_graph_version}</dd></div><div><dt>Traffic snapshot</dt><dd>{route.snapshot_version || 'Not returned'}</dd></div><div><dt>Expanded nodes</dt><dd>{route.expanded_nodes ? route.expanded_nodes.toLocaleString() : 'Not returned'}</dd></div><div><dt>Edge IDs</dt><dd>{route.edge_ids.length ? route.edge_ids.length.toLocaleString() : 'Not returned'}</dd></div></dl><p className="snapshot-note"><Gauge /> The calculation used one immutable cost snapshot. Concurrent traffic refreshes did not alter this search.</p></details><details><summary>Coordinates and waypoints</summary><p><strong>Start:</strong> {formatCoordinates(route.waypoints[0]?.latitude, route.waypoints[0]?.longitude)}</p><p><strong>End:</strong> {formatCoordinates(route.waypoints.at(-1)?.latitude, route.waypoints.at(-1)?.longitude)}</p><ol className="waypoint-list">{route.waypoints.map((point, index) => <li key={`${point.latitude}:${point.longitude}:${index}`}><span>{index + 1}</span><code>{formatCoordinates(point.latitude, point.longitude)}</code></li>)}</ol></details>{persisted && <div className="persisted-warning"><CheckCircle2 /><span><strong>Immutable inspection</strong>This view does not recalculate or mutate the command route.</span></div>}</div>;
}
