import { ArrowLeft, Clock3, Hash, RotateCcw, StopCircle } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useState } from 'react';
import { AcknowledgementCard, CommandAttemptSummary, CommandPayloadViewer, ExecutionResultCard } from '../components/operations/CommandDetails';
import { ConfirmationDialog } from '../components/operations/ConfirmationDialog';
import { EntityLink } from '../components/operations/EntityLink';
import { CommandLifecycleTimeline } from '../components/operations/LifecycleTimeline';
import { CommandStatusBadge } from '../components/operations/OperationsStatus';
import { ErrorState, PageLoader } from '../components/ui/States';
import { useAuth } from '../features/auth/AuthContext';
import { canCancelCommandState, canRetryCommandState } from '../features/operations/model';
import { useCommand } from '../features/operations/queries';
import { readableError } from '../lib/api/errors';
import { exactTime } from '../lib/format';
import { can } from '../lib/permissions';
import { useQueryClient } from '../lib/query/queryClient';
import { useTwin } from '../features/fleet/queries';

export default function CommandDetail(){const{commandId=''}=useParams();const[params]=useSearchParams();const{session,api}=useAuth();const queryClient=useQueryClient();const commandQuery=useCommand(commandId);const[action,setAction]=useState<'cancel'|'retry'|null>(null);const[working,setWorking]=useState(false);const[actionError,setActionError]=useState<unknown>();
  const deviceTwin=useTwin(commandQuery.data?.device_id||'');
  if(commandQuery.isLoading)return <PageLoader label="Loading command"/>;if(commandQuery.error||!commandQuery.data)return <ErrorState error={commandQuery.error||new Error('Command was not found.')} retry={()=>void commandQuery.refetch()}/>;const command=commandQuery.data;const back=`/commands${params.get('return')?`?${params.get('return')}`:''}`;
  const mutate=async()=>{if(!api||!action)return;setWorking(true);setActionError(undefined);try{if(action==='cancel')await api.cancelCommand(commandId);else await api.retryCommand(commandId);setAction(null);queryClient.refresh(['command',session!.tenantId,commandId]);queryClient.refresh(['commands',session!.tenantId]);queryClient.refresh(['task',session!.tenantId,command.task_id]);queryClient.refresh(['tasks',session!.tenantId]);}catch(error){setActionError(error);}finally{setWorking(false);}};const error=actionError?readableError(actionError):null;
  return <div className="page-stack operation-detail"><Link className="back-link" to={back}><ArrowLeft/> Back to commands</Link><header className="operation-hero"><div><p className="eyebrow">Immutable device instruction</p><h1>{command.command_type}</h1><code>{command.command_id}</code></div><CommandStatusBadge status={command.status}/><div className="operation-actions">{session&&can(session.role,'cancelCommand')&&<button className="button secondary" disabled={!canCancelCommandState(command.status)} title="Cancellation is valid only before delivery." onClick={()=>setAction('cancel')}><StopCircle/> Cancel before delivery</button>}{session&&can(session.role,'retryCommand')&&<button className="button secondary" disabled={!canRetryCommandState(command.status)} title="Administrative delivery retry supports delivered or failed commands subject to backend constraints." onClick={()=>setAction('retry')}><RotateCcw/> Retry delivery</button>}</div></header>
    {error&&<div className="inline-error"><strong>{error.status===409?'The durable command state no longer permits this operation.':error.code||'Operation failed'}</strong><span>{error.status===409?'Refresh and review the current lifecycle, expiry, attempts, and reservation state.':error.message}</span>{error.requestId&&<small>Request ID: {error.requestId}</small>}</div>}
    {command.status==='PENDING'&&command.attempt_count>0&&<div className="pending-callout"><Clock3/><div><strong>Waiting for the next delivery opportunity</strong><span>The command remains durable. At-least-once delivery reuses the same identity and sequence.</span></div></div>}
    {command.status==='PENDING'&&deviceTwin.data&&deviceTwin.data.connectivity.status!=='ONLINE'&&<div className="pending-callout"><Clock3/><div><strong>Waiting for device connectivity</strong><span>The device is currently {deviceTwin.data.connectivity.status.toLowerCase().replace('_',' ')}. This command remains durable and may be delivered when the device reconnects.</span></div></div>}
    <div className="command-identity-grid"><div><Hash/><span><small>Device sequence</small><strong>{command.sequence_number}</strong></span><p>Later outstanding commands cannot overtake this command while it is the lowest unfinished sequence.</p></div><EntityLink label="Task" id={command.task_id} to={`/tasks/${command.task_id}`}/><EntityLink label="Device" id={command.device_id} to={`/devices/${command.device_id}`}/></div>
    <div className="operation-detail-grid"><section className="panel"><div className="panel-title"><h2>Command lifecycle</h2><span>Runtime-confirmed milestones only</span></div><CommandLifecycleTimeline command={command}/><details className="architecture-flow"><summary>Advanced delivery architecture</summary><p>Command persisted → outbox publication → Kafka transport → dispatcher → gateway delivery → device ACK → device result.</p><small>These are architecture steps, not per-command trace evidence unless a durable timestamp above confirms them.</small></details></section><section className="panel"><div className="panel-title"><h2>Command metadata</h2><span>Version {command.version}</span></div><dl className="operation-metadata"><div><dt>Tenant</dt><dd><code>{command.tenant_id}</code></dd></div><div><dt>Created</dt><dd>{exactTime(command.created_at)}</dd></div><div><dt>Expires</dt><dd>{exactTime(command.expires_at)}</dd></div><div><dt>Correlation ID</dt><dd><code>{command.correlation_id}</code></dd></div><div><dt>Causation ID</dt><dd><code>{command.causation_id}</code></dd></div><div><dt>Schema version</dt><dd>Not exposed by command read API</dd></div></dl></section></div>
    <section className="panel"><div className="panel-title"><h2>Payload</h2><span>Read-only</span></div><CommandPayloadViewer command={command}/></section><div className="operation-detail-grid"><section className="panel"><div className="panel-title"><h2>Delivery attempts</h2><span>Aggregate read model</span></div><CommandAttemptSummary command={command}/></section><section className="panel"><div className="panel-title"><h2>Device acknowledgement</h2><span>ACK advances durable state</span></div><AcknowledgementCard command={command}/></section></div><section className="panel"><div className="panel-title"><h2>Execution result</h2><span>Terminal device result</span></div><ExecutionResultCard command={command}/></section>
    <ConfirmationDialog open={action==='cancel'} title="Cancel command before delivery?" confirmLabel="Cancel pending command" danger working={working} onClose={()=>!working&&setAction(null)} onConfirm={()=>void mutate()}><p>This delegates to conservative task cancellation. It is valid only while this command remains PENDING.</p><p>Cancellation does not mean a physical device stopped after receiving work.</p></ConfirmationDialog><ConfirmationDialog open={action==='retry'} title="Retry immutable command delivery?" confirmLabel="Retry same command" working={working} onClose={()=>!working&&setAction(null)} onConfirm={()=>void mutate()}><p>This reuses command <code>{command.command_id}</code>, device sequence {command.sequence_number}, and the exact persisted payload.</p><p>A FAILED command may reactivate its existing assignment only when the backend can reserve that device and the command has not expired. No new assignment decision or command identity is created.</p></ConfirmationDialog>
  </div>}
