import { ArrowLeft, ArrowRight, Battery, Check, CheckCircle2, Cpu, MapPin, Navigation, Route, Send, Shapes, Timer } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { TaskPriorityBadge, TaskStatusBadge } from '../components/operations/OperationsStatus';
import { TaskTimingDiagnostics } from '../components/operations/TaskDetails';
import { PageHeader } from '../components/ui/PageHeader';
import { useAuth } from '../features/auth/AuthContext';
import { useCapabilities, useProjects } from '../features/fleet/queries';
import { deviceTypes, priorityDescription, requiredCapability, taskPriorities, taskTypes, titleCase, validateTaskDraft, type TaskDraft } from '../features/operations/model';
import { deviceTypeLabel, exactTime, formatCoordinates } from '../lib/format';
import { readableError } from '../lib/api/errors';
import { can } from '../lib/permissions';
import type { CreateTaskResult, PlanningMode } from '../types/domain';

const steps = ['Task', 'Target', 'Requirements', 'Planning', 'Review'];
function localExpiry() { const date = new Date(Date.now() + 5 * 60_000); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0,16); }

export default function CreateTask() {
  const { session, api } = useAuth();
  const projects = useProjects();
  const capabilities = useCapabilities();
  const [step, setStep] = useState(0);
  const [draft, setDraft] = useState<TaskDraft>({ projectId:'',taskType:'NAVIGATE',priority:'NORMAL',expiresAt:localExpiry(),latitude:'13.0827',longitude:'80.2707',targetJSON:'{}',minimumBattery:'',maximumDistanceKm:'',deviceTypes:[],optionalCapabilities:[],planningMode:'DEVICE_LOCAL',customConstraintsJSON:'',correlationId:'' });
  const [errors, setErrors] = useState<Record<string,string>>({});
  const [working,setWorking]=useState(false);
  const [failure,setFailure]=useState<unknown>();
  const [result,setResult]=useState<CreateTaskResult>();
  const validation=useMemo(()=>validateTaskDraft(draft),[draft]);
  const automatic=requiredCapability(draft.taskType);
  const spatial=draft.taskType==='NAVIGATE'||draft.taskType==='RELOCATE';
  if (!session || !can(session.role,'createTask')) return <div className="page-state error-state"><strong>Task creation is not available</strong><span>Your authenticated backend role must permit orchestration.</span><Link className="button secondary" to="/tasks">Return to tasks</Link></div>;
  const patch=<K extends keyof TaskDraft>(key:K,value:TaskDraft[K])=>{setDraft(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:''}));};
  const toggle=(key:'deviceTypes'|'optionalCapabilities',value:string)=>patch(key,draft[key].includes(value)?draft[key].filter(item=>item!==value):[...draft[key],value]);
  const submit=async()=>{setErrors(validation.errors);if(!validation.input||!api)return;setWorking(true);setFailure(undefined);try{setResult(await api.createTask(validation.input,draft.correlationId.trim()||undefined));setStep(steps.length);}catch(error){setFailure(error);}finally{setWorking(false);}};
  if(result)return <div className="page-stack"><PageHeader eyebrow="Durable task accepted" title="Task created" description={result.command?'Polaris selected an eligible device and persisted an immutable command.':'The task is durable and waiting for a currently eligible device.'}/><section className="creation-result"><span className="result-symbol"><CheckCircle2/></span><div><TaskStatusBadge status={result.task.status}/><h2>{result.task.task_type}</h2><code>{result.task.task_id}</code>{!result.command&&<p>Waiting for an eligible device. Reconciliation will reconsider this task while it remains pending and unexpired.</p>}</div></section><div className="result-links"><Link className="button primary" to={`/tasks/${result.task.task_id}`}>Open task <ArrowRight/></Link>{result.command&&<Link className="button secondary" to={`/commands/${result.command.command_id}`}>Open command <ArrowRight/></Link>}<Link className="button ghost" to="/tasks">All tasks</Link></div><section className="panel"><div className="panel-title"><h2>Orchestration timing</h2><span>Request-scoped diagnostic</span></div><TaskTimingDiagnostics timing={result.timing}/></section></div>;
  return <div className="page-stack create-task-page"><PageHeader eyebrow="New operator intent" title="Create task" description="Define work and constraints; Polaris remains authoritative for eligibility, assignment, planning, and persistence."/><div className="wizard-shell"><nav className="wizard-steps" aria-label="Task creation progress">{steps.map((label,index)=><button key={label} className={index===step?'active':index<step?'complete':''} onClick={()=>index<step&&setStep(index)} disabled={index>step}><span>{index<step?<Check/>:index+1}</span>{label}</button>)}</nav><section className="wizard-panel">
    {step===0&&<div className="wizard-section"><div className="step-heading"><Shapes/><div><p className="eyebrow">Step 1</p><h2>Basic task information</h2></div></div><div className="form-grid"><label>Project<select value={draft.projectId} onChange={event=>patch('projectId',event.target.value)}><option value="">Any project</option>{projects.data?.map(project=><option value={project.project_id} key={project.project_id}>{project.name}</option>)}</select></label><label>Task type<select value={draft.taskType} onChange={event=>patch('taskType',event.target.value)}>{taskTypes.map(type=><option key={type}>{type}</option>)}</select>{errors.taskType&&<small className="field-error">{errors.taskType}</small>}</label><fieldset className="priority-picker"><legend>Priority</legend>{taskPriorities.map(priority=><label key={priority}><input type="radio" checked={draft.priority===priority} onChange={()=>patch('priority',priority)}/><TaskPriorityBadge priority={priority}/><span>{priorityDescription(priority)}</span></label>)}</fieldset><label>Expires at<input type="datetime-local" value={draft.expiresAt} onChange={event=>patch('expiresAt',event.target.value)}/>{errors.expiresAt&&<small className="field-error">{errors.expiresAt}</small>}</label><label>Correlation ID <small>Optional</small><input value={draft.correlationId} onChange={event=>patch('correlationId',event.target.value)} placeholder="Generated by Polaris when blank"/></label></div></div>}
    {step===1&&<div className="wizard-section"><div className="step-heading"><MapPin/><div><p className="eyebrow">Step 2</p><h2>Task target</h2></div></div>{spatial?<div className="form-grid two"><label>Destination latitude<input type="number" step="any" value={draft.latitude} onChange={event=>patch('latitude',event.target.value)}/>{errors.latitude&&<small className="field-error">{errors.latitude}</small>}</label><label>Destination longitude<input type="number" step="any" value={draft.longitude} onChange={event=>patch('longitude',event.target.value)}/>{errors.longitude&&<small className="field-error">{errors.longitude}</small>}</label><div className="coordinate-preview"><MapPin/><span><small>Target preview</small><strong>{formatCoordinates(Number(draft.latitude),Number(draft.longitude))}</strong></span></div></div>:<label className="json-field">Target document<textarea value={draft.targetJSON} onChange={event=>patch('targetJSON',event.target.value)} spellCheck={false}/><small>Use the backend-defined parameters for {draft.taskType}. The document must be a JSON object.</small>{errors.targetJSON&&<span className="field-error">{errors.targetJSON}</span>}</label>}</div>}
    {step===2&&<div className="wizard-section"><div className="step-heading"><Cpu/><div><p className="eyebrow">Step 3</p><h2>Device requirements</h2></div></div><div className="automatic-capability"><Navigation/><span><small>Required automatically by command type</small><strong>{automatic}</strong></span><b>Locked</b></div><fieldset className="choice-grid"><legend>Allowed device types <small>Optional</small></legend>{deviceTypes.map(type=><label key={type}><input type="checkbox" checked={draft.deviceTypes.includes(type)} onChange={()=>toggle('deviceTypes',type)}/><Shapes/><span>{deviceTypeLabel(type)}</span></label>)}</fieldset><div className="form-grid two"><label>Minimum battery (%)<input type="number" min="0" max="100" step="1" value={draft.minimumBattery} onChange={event=>patch('minimumBattery',event.target.value)} placeholder="No minimum"/>{errors.minimumBattery&&<small className="field-error">{errors.minimumBattery}</small>}</label><label>Maximum target distance (km)<input type="number" min="0" step="0.1" value={draft.maximumDistanceKm} onChange={event=>patch('maximumDistanceKm',event.target.value)} placeholder="No maximum"/>{errors.maximumDistanceKm&&<small className="field-error">{errors.maximumDistanceKm}</small>}</label></div><fieldset className="choice-grid capabilities"><legend>Additional capabilities <small>Optional</small></legend>{capabilities.data?.filter(cap=>cap.capability_id!==automatic).map(cap=><label key={cap.capability_id}><input type="checkbox" checked={draft.optionalCapabilities.includes(cap.capability_id)} onChange={()=>toggle('optionalCapabilities',cap.capability_id)}/><Cpu/><span>{cap.display_name}<small>{cap.capability_id}</small></span></label>)}</fieldset><label className="json-field compact">Custom constraints <small>Optional advanced JSON object</small><textarea value={draft.customConstraintsJSON} onChange={event=>patch('customConstraintsJSON',event.target.value)} spellCheck={false}/>{errors.customConstraintsJSON&&<span className="field-error">{errors.customConstraintsJSON}</span>}</label></div>}
    {step===3&&<div className="wizard-section"><div className="step-heading"><Route/><div><p className="eyebrow">Step 4</p><h2>Planning responsibility</h2></div></div>{spatial?<fieldset className="planning-picker"><legend>Planning mode</legend>{(['DEVICE_LOCAL','POLARIS_REQUIRED'] as PlanningMode[]).map(mode=><label key={mode}><input type="radio" checked={draft.planningMode===mode} onChange={()=>patch('planningMode',mode)}/><span className="planning-icon">{mode==='DEVICE_LOCAL'?<Navigation/>:<Route/>}</span><span><strong>{titleCase(mode)}</strong><small>{mode==='DEVICE_LOCAL'?'Polaris sends the high-level destination; the device performs compatible local planning.':'Polaris must generate a valid platform route before the task can be committed to a device.'}</small></span></label>)}</fieldset>:<div className="compact-empty"><Navigation/><span>{draft.taskType} uses the generic Polaris planner. Planning mode is not accepted for this task type.</span></div>}<p className="architecture-note"><Route/> POLARIS_REQUIRED currently supports road-vehicle routing. Polaris will return an explicit planner/profile error rather than silently falling back.</p></div>}
    {step===4&&<div className="wizard-section"><div className="step-heading"><Send/><div><p className="eyebrow">Step 5</p><h2>Review durable intent</h2></div></div><div className="review-grid"><div><span>Task type</span><strong>{draft.taskType}</strong></div><div><span>Priority</span><TaskPriorityBadge priority={draft.priority}/></div><div><span>Project</span><strong>{projects.data?.find(project=>project.project_id===draft.projectId)?.name||'Any project'}</strong></div><div><span>Expiry</span><strong>{exactTime(draft.expiresAt)}</strong></div><div><span>Planning</span><strong>{spatial?titleCase(draft.planningMode):'Generic planner'}</strong></div><div><span>Target</span><strong>{spatial?formatCoordinates(Number(draft.latitude),Number(draft.longitude)):'Structured document'}</strong></div></div><div className="eligibility-review"><h3>Polaris will consider devices that</h3><ul><li><Check/> belong to this tenant and are ACTIVE</li><li><Check/> are ONLINE with current state</li><li><Check/> have <strong>{automatic}</strong> capability</li><li><Check/> have no exclusive active assignment</li>{draft.projectId&&<li><Check/> belong to the selected project</li>}{draft.deviceTypes.length>0&&<li><Check/> match an allowed device type</li>}{Number(draft.minimumBattery)>0&&<li><Battery/> report at least {draft.minimumBattery}% battery</li>}{Number(draft.maximumDistanceKm)>0&&<li><MapPin/> are within {draft.maximumDistanceKm} km of the target</li>}</ul><p>This is not a candidate preview. The backend evaluates and reserves eligibility atomically after submission.</p></div>{Object.keys(validation.errors).length>0&&<div className="inline-error"><strong>Review the invalid fields before creating this task.</strong>{Object.values(validation.errors).map(message=><small key={message}>{message}</small>)}</div>}{Boolean(failure)&&(()=>{const value=readableError(failure);return <div className="inline-error"><strong>{value.code||'Task creation failed'}</strong><span>{value.message}</span>{value.requestId&&<small>Request ID: {value.requestId}</small>}</div>;})()}</div>}
    <footer className="wizard-actions"><button className="button secondary" disabled={step===0||working} onClick={()=>setStep(value=>value-1)}><ArrowLeft/> Back</button><span>Step {step+1} of {steps.length}</span>{step<steps.length-1?<button className="button primary" onClick={()=>setStep(value=>value+1)}>Continue <ArrowRight/></button>:<button className="button primary" disabled={working} onClick={()=>void submit()}>{working?<><Timer/> Creating durable task…</>:<><Send/> Create task</>}</button>}</footer>
  </section></div></div>;
}
