import { AlertTriangle, FlaskConical } from 'lucide-react';
import { PolarisMap } from '../components/map/PolarisMap';
import { MobilityNav } from '../components/mobility/MobilityNav';
import { PageHeader } from '../components/ui/PageHeader';
import { ErrorState, PageLoader } from '../components/ui/States';
import { useAuth } from '../features/auth/AuthContext';
import { usePredictedZones } from '../features/mobility/queries';

export default function MobilityExperimental(){const{session}=useAuth();const query=usePredictedZones();const zones=(query.data||[]).filter(zone=>zone.tenant_id===session?.tenantId);return <div className="page-stack mobility-page"><PageHeader eyebrow="Compatibility analytics" title="Experimental Analytics" description="A deliberately isolated view of the existing historical density heuristic."/><MobilityNav/><div className="experimental-banner"><AlertTriangle/><div><strong>Legacy Density Heuristic</strong><span>This is not machine learning, demand forecasting, or autonomous fleet rebalancing.</span></div></div>{query.isLoading?<PageLoader label="Loading predicted zones"/>:query.error?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:<><div className="experimental-layout"><section className="panel"><div className="panel-title"><h2>Active-tenant zones</h2><span>{zones.length} returned after client safety filtering</span></div>{zones.length?zones.map(zone=><article className="zone-row" key={zone.id}><FlaskConical/><span><strong>{zone.id}</strong><small>{zone.lat.toFixed(4)}, {zone.lon.toFixed(4)} · {zone.radius_km} km radius</small></span><b>{zone.required_assets} nominal assets</b></article>):<div className="compact-empty"><FlaskConical/><span>No predicted zones are available for the active tenant.</span></div>}</section><div className="mobility-map-wrap"><PolarisMap zones={zones} fitKey={`zones:${zones.map(zone=>zone.id).join(',')}`}/></div></div><section className="panel"><h2>Current limitations</h2><p>The backend groups telemetry from the last hour into coordinates rounded to two decimal places and returns up to three dense cells. Radius and required asset count are fixed nominal values. It never issues tasks or commands.</p><p>The current SQL is not tenant-filtered and the emitted tenant identity is hard-coded. This frontend suppresses zones that do not match the active tenant, but the endpoint still requires a backend tenant-authority fix before production analytics use.</p></section></>}</div>}
