import { ChevronRight, LocateFixed, Search, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { PolarisMap, type MapDeviceMarker } from '../components/map/PolarisMap';
import { CoordinateFields, ProfileBadge } from '../components/mobility/MobilityUi';
import { MobilityNav } from '../components/mobility/MobilityNav';
import { PageHeader } from '../components/ui/PageHeader';
import { ErrorState, TableSkeleton } from '../components/ui/States';
import { useTwin } from '../features/fleet/queries';
import { formatDistance, positionFreshness, validateNearby } from '../features/mobility/model';
import { useNearby } from '../features/mobility/queries';
import { formatCoordinates, relativeTime } from '../lib/format';
import type { MobilityPosition, NearbySearch as NearbyInput, SpatialCandidate } from '../types/domain';

export default function NearbySearch() {
  const [origin, setOrigin] = useState<MobilityPosition>({ latitude: 13.0827, longitude: 80.2707 }); const [radiusKm, setRadiusKm] = useState(5); const [limit, setLimit] = useState(20); const [submitted, setSubmitted] = useState<NearbyInput>(); const [errors, setErrors] = useState<Record<string,string>>({}); const [selecting, setSelecting] = useState(false); const [selected, setSelected] = useState<SpatialCandidate>();
  const query = useNearby(submitted); const twin = useTwin(selected?.state.device_id || '');
  useEffect(() => { if (submitted && (submitted.latitude !== origin.latitude || submitted.longitude !== origin.longitude || submitted.radiusMeters !== radiusKm * 1000 || submitted.limit !== limit)) { const frame=window.requestAnimationFrame(()=>{setSubmitted(undefined);setSelected(undefined);});return()=>window.cancelAnimationFrame(frame); } }, [origin, radiusKm, limit, submitted]);
  const markers = useMemo<MapDeviceMarker[]>(() => (query.data?.devices || []).map(item => ({ id: item.state.device_id, label: item.state.device_id, position: item.state.position, profile: item.state.mobility_profile })), [query.data]);
  const submit = () => { const radiusMeters = radiusKm * 1000; const found = validateNearby(origin.latitude, origin.longitude, radiusMeters, limit); setErrors(found); if (!Object.keys(found).length) { setSelected(undefined); const next={ ...origin, radiusMeters, limit }; if(submitted&&JSON.stringify(submitted)===JSON.stringify(next))void query.refetch();else setSubmitted(next); } };
  return <div className="page-stack mobility-page"><PageHeader eyebrow="Canonical geographic discovery" title="Nearby Search" description="Query the tenant-aware H3 and packed R-tree index, followed by exact Haversine verification." /><MobilityNav /><div className="mobility-workspace"><aside className="mobility-controls"><CoordinateFields label="Search origin" value={origin} onChange={setOrigin} selecting={selecting} onSelectMode={() => setSelecting(value => !value)} error={errors.coordinates}/><label>Radius (km)<input type="number" min="0.1" max="10" step="0.1" value={radiusKm} onChange={event => setRadiusKm(Number(event.target.value))}/>{errors.radius && <small className="field-error">{errors.radius}</small>}</label><label>Result limit<input type="number" min="1" max="50" step="1" value={limit} onChange={event => setLimit(Number(event.target.value))}/>{errors.limit && <small className="field-error">{errors.limit}</small>}</label><button className="button primary" onClick={submit}><Search/> {submitted ? 'Search again' : 'Search nearby'}</button><div className="query-facts"><span><small>Origin</small><code>{formatCoordinates(origin.latitude, origin.longitude)}</code></span><span><small>Radius</small><strong>{radiusKm} km</strong></span></div><p className="bounded-note">Deployment defaults cap this query at 10 km and 50 results. The backend does not currently expose those configured limits dynamically.</p></aside><div className="mobility-map-wrap"><PolarisMap devices={markers} selectedId={selected?.state.device_id} onDeviceSelect={id => setSelected(query.data?.devices.find(item => item.state.device_id === id))} selectionMode={selecting ? 'SEARCH' : undefined} onMapSelect={point => { if (selecting) { setOrigin(point); setSelecting(false); } }} origin={origin} searchRadiusMeters={submitted?.radiusMeters || radiusKm * 1000} fitKey={submitted ? `nearby:${submitted.latitude}:${submitted.longitude}:${submitted.radiusMeters}` : 'nearby-initial'}/><div className="map-layer-note"><span><i className="layer-dot origin"/>Search origin</span><span><i className="layer-dot device"/>Indexed device position</span><span className="disabled"><i/>Traffic layer unavailable</span></div></div></div>
    <section className="panel"><div className="panel-title"><div><h2>Nearby devices</h2><span>{query.data ? `${query.data.count} returned in backend distance order` : 'Run a point-in-time search'}</span></div></div>{query.isLoading && submitted ? <TableSkeleton rows={5}/> : query.error ? <ErrorState error={query.error} retry={() => void query.refetch()}/> : query.data && !query.data.devices.length ? <div className="compact-empty"><LocateFixed/><span>No devices found within this search radius.</span></div> : query.data ? <div className="table-scroll"><table className="data-table nearby-table"><thead><tr><th>Device</th><th>Profile</th><th>Direct distance</th><th>Indexed position</th><th>Observed</th><th/></tr></thead><tbody>{query.data.devices.map(item => <tr key={item.state.device_id} className={selected?.state.device_id === item.state.device_id ? 'selected-row' : ''} onClick={() => setSelected(item)}><td><strong>{item.state.device_id}</strong>{item.state.quality.anomalies?.length ? <small className="quality-warning">{item.state.quality.anomalies.join(', ')}</small> : null}</td><td><ProfileBadge profile={item.state.mobility_profile}/></td><td>{formatDistance(item.distance_meters)}</td><td><code>{formatCoordinates(item.state.position.latitude,item.state.position.longitude)}</code></td><td>{relativeTime(item.state.observed_at)}</td><td><ChevronRight/></td></tr>)}</tbody></table></div> : <div className="compact-empty"><Search/><span>Choose coordinates and search. Results are not silently refreshed.</span></div>}</section>
    {selected && <aside className="mobility-drawer"><button onClick={() => setSelected(undefined)} aria-label="Close device details"><X/></button><p className="eyebrow">Nearby spatial result</p><h2>{twin.data?.device.display_name || selected.state.device_id}</h2><ProfileBadge profile={selected.state.mobility_profile}/><dl><div><dt>Distance</dt><dd>{formatDistance(selected.distance_meters)}</dd></div><div><dt>Connectivity</dt><dd>{twin.data?.connectivity.status || 'Not returned by nearby search'}</dd></div><div><dt>Position meaning</dt><dd>{twin.data ? positionFreshness(twin.data.connectivity.status) : 'Indexed Mobility position'}</dd></div><div><dt>Reported position</dt><dd>{formatCoordinates(selected.state.reported_position.latitude,selected.state.reported_position.longitude)}</dd></div><div><dt>Indexed position</dt><dd>{formatCoordinates(selected.state.position.latitude,selected.state.position.longitude)}</dd></div></dl><details><summary>Advanced spatial details</summary><p>H3 cell: <code>{selected.state.h3_cell}</code></p><p>Indexed {relativeTime(selected.state.indexed_at)}</p><p>Quality confidence: {(selected.state.quality.confidence * 100).toFixed(0)}%</p></details><Link className="button primary" to={`/devices/${encodeURIComponent(selected.state.device_id)}`}>Open device</Link></aside>}
  </div>;
}
