import { Activity, Box, ListTodo, Search } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { CommandStatusBadge, TaskStatusBadge } from '../components/operations/OperationsStatus';
import { EmptyState, ErrorState, TableSkeleton } from '../components/ui/States';
import { PageHeader } from '../components/ui/PageHeader';
import { useCommands, useTasks } from '../features/operations/queries';
import { exactTime, relativeTime } from '../lib/format';

export default function OperationsActivity(){const[params,setParams]=useSearchParams();const tasks=useTasks({},100,'',true);const commands=useCommands({},100,'',true);const kind=params.get('kind')||'';const state=params.get('state')?.toUpperCase()||'';const device=params.get('device')?.toLowerCase()||'';
  if(tasks.isLoading||commands.isLoading)return <TableSkeleton/>;if(tasks.error||commands.error)return <ErrorState error={tasks.error||commands.error} retry={()=>{void tasks.refetch();void commands.refetch();}}/>;
  const entries=[...(tasks.data||[]).map(task=>({id:`task-${task.task_id}`,kind:'TASK' as const,entityId:task.task_id,relatedId:'',deviceId:task.assigned_device_id||'',state:task.status,observedAt:task.updated_at||task.created_at,label:task.task_type})),...(commands.data||[]).map(command=>({id:`command-${command.command_id}`,kind:'COMMAND' as const,entityId:command.command_id,relatedId:command.task_id,deviceId:command.device_id,state:command.status,observedAt:command.completed_at||command.acknowledged_at||command.sent_at||command.created_at,label:command.command_type}))].filter(item=>(!kind||item.kind===kind)&&(!state||item.state===state)&&(!device||item.deviceId.toLowerCase().includes(device))).sort((a,b)=>Date.parse(b.observedAt)-Date.parse(a.observedAt));
  const update=(name:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(name,value);else next.delete(name);setParams(next);};
  return <div className="page-stack"><PageHeader eyebrow="Current durable snapshot" title="Operations activity" description="The latest task and command states from bounded REST hydration; this is not historical audit or a lifecycle event stream." actions={<span className="loaded-scope">Refreshes every 10 seconds</span>}/><div className="activity-disclaimer"><Activity/><span><strong>No browser lifecycle stream exists.</strong> Changes become visible through controlled polling while this page is open. Reloading reconstructs current state, not prior transitions.</span></div><div className="operation-filters"><select value={kind} onChange={event=>update('kind',event.target.value)} aria-label="Filter activity type"><option value="">Tasks and commands</option><option value="TASK">Tasks</option><option value="COMMAND">Commands</option></select><label><Search/><input value={state} onChange={event=>update('state',event.target.value)} placeholder="Exact current state" aria-label="Filter by current state"/></label><label><Search/><input value={params.get('device')||''} onChange={event=>update('device',event.target.value)} placeholder="Device ID contains" aria-label="Filter by device"/></label>{params.size>0&&<button onClick={()=>setParams({})}>Clear</button>}</div>{!entries.length?<EmptyState title="No current operations match" message="Adjust the filters or create durable work from the Tasks page."/>:<div className="operations-activity-list">{entries.map(item=><Link key={item.id} to={item.kind==='TASK'?`/tasks/${item.entityId}`:`/commands/${item.entityId}`}><span className={`activity-entity ${item.kind.toLowerCase()}`}>{item.kind==='TASK'?<ListTodo/>:<Box/>}</span><span><small>{item.kind} · {item.label}</small><strong>{item.entityId}</strong>{item.deviceId&&<code>{item.deviceId}</code>}</span>{item.kind==='TASK'?<TaskStatusBadge status={item.state}/>:<CommandStatusBadge status={item.state}/>}<time title={exactTime(item.observedAt)}>{relativeTime(item.observedAt)}</time></Link>)}</div>}</div>;
}
