import { ArrowLeft, GitCompare, LoaderCircle, Route as RouteIcon } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { PolarisMap } from '../components/map/PolarisMap';
import { CoordinateFields, ProfileBadge, RouteErrorCard, RouteSummary } from '../components/mobility/MobilityUi';
import { MobilityNav } from '../components/mobility/MobilityNav';
import { PageHeader } from '../components/ui/PageHeader';
import { ErrorState, PageLoader } from '../components/ui/States';
import { useAuth } from '../features/auth/AuthContext';
import { persistedCommandRoute, routePolicies, validateRoute } from '../features/mobility/model';
import { useCommand } from '../features/operations/queries';
import type { MobilityPosition, MobilityProfile, RoutePolicy, RouteRequest, RouteResult } from '../types/domain';

export default function RouteExplorer() {
  const { api } = useAuth(); const [params] = useSearchParams(); const commandId = params.get('command_id') || ''; const commandQuery = useCommand(commandId); const persisted = persistedCommandRoute(commandQuery.data);
  const [origin,setOrigin]=useState<MobilityPosition>({latitude:13.0827,longitude:80.2707}); const[destination,setDestination]=useState<MobilityPosition>({latitude:13.0067,longitude:80.2206}); const[profile,setProfile]=useState<MobilityProfile>('ROAD_VEHICLE'); const[policy,setPolicy]=useState<RoutePolicy>('FASTEST'); const[selection,setSelection]=useState<'ORIGIN'|'DESTINATION'>(); const[errors,setErrors]=useState<Record<string,string>>({}); const[requestError,setRequestError]=useState<unknown>(); const[working,setWorking]=useState(false); const[result,setResult]=useState<RouteResult>(); const[comparison,setComparison]=useState<{shortest:RouteResult;fastest:RouteResult}>(); const[visible,setVisible]=useState<RoutePolicy>('FASTEST');
  useEffect(()=>{const frame=window.requestAnimationFrame(()=>{setResult(undefined);setComparison(undefined);setRequestError(undefined);});return()=>window.cancelAnimationFrame(frame);},[origin,destination,profile,policy]);
  const calculate = async (compare=false) => { if (!api) return; const base:RouteRequest={mobility_profile:profile,origin,destination,policy}; const invalid=validateRoute(base);setErrors(invalid);if(Object.keys(invalid).length)return;setWorking(true);setRequestError(undefined);setComparison(undefined);try{if(compare){const[shortest,fastest]=await Promise.all([api.route({...base,policy:'SHORTEST'}),api.route({...base,policy:'FASTEST'})]);setComparison({shortest,fastest});setResult(fastest);setVisible('FASTEST');}else{const route=await api.route(base);setResult(route);setVisible(route.policy);}}catch(error){setResult(undefined);setRequestError(error);}finally{setWorking(false);}};
  const displayed = persisted || (comparison ? (visible==='FASTEST'?comparison.fastest:comparison.shortest) : result); const routeLayers = useMemo(()=>displayed?[{route:displayed}]:[],[displayed]);
  if(commandId&&commandQuery.isLoading)return <PageLoader label="Loading persisted command route"/>;
  return <div className="page-stack mobility-page"><PageHeader eyebrow="Bounded A* road routing" title={persisted?'Persisted Command Route':'Route Explorer'} description={persisted?'Inspect the exact immutable route stored in the command. It will not be recalculated.':'Calculate a point-in-time route against one immutable traffic-cost snapshot.'} actions={persisted?<Link className="button secondary" to={`/commands/${encodeURIComponent(commandId)}`}><ArrowLeft/>Command</Link>:undefined}/><MobilityNav/>{commandId&&commandQuery.error?<ErrorState error={commandQuery.error} retry={()=>void commandQuery.refetch()}/>:<div className="mobility-workspace route-workspace">{!persisted&&<aside className="mobility-controls"><CoordinateFields label="Origin" value={origin} onChange={setOrigin} selecting={selection==='ORIGIN'} onSelectMode={()=>setSelection(selection==='ORIGIN'?undefined:'ORIGIN')} error={errors.origin}/><CoordinateFields label="Destination" value={destination} onChange={setDestination} selecting={selection==='DESTINATION'} onSelectMode={()=>setSelection(selection==='DESTINATION'?undefined:'DESTINATION')} error={errors.destination}/><label>Mobility profile<select value={profile} onChange={event=>setProfile(event.target.value as MobilityProfile)}><option value="ROAD_VEHICLE">Road vehicle</option><option value="GROUND_ROBOT">Ground robot</option><option value="AERIAL_DRONE">Aerial drone</option><option value="STATIC">Static spatial device</option></select></label><ProfileBadge profile={profile}/>{errors.profile&&<small className="field-error">{errors.profile}</small>}<fieldset className="policy-picker"><legend>Route policy</legend>{routePolicies.map(item=><label key={item}><input type="radio" checked={policy===item} onChange={()=>setPolicy(item)}/><span><strong>{item==='FASTEST'?'Fastest time':'Shortest distance'}</strong><small>{item==='FASTEST'?'Uses the current route-cost snapshot.':'Minimizes route distance.'}</small></span></label>)}</fieldset><button className="button primary" disabled={working} onClick={()=>void calculate(false)}>{working?<LoaderCircle className="spin"/>:<RouteIcon/>}{working?'Calculating route…':'Calculate route'}</button><button className="button secondary" disabled={working} onClick={()=>void calculate(true)}><GitCompare/>Compare policies</button></aside>}<div className="mobility-map-wrap"><PolarisMap origin={persisted?.waypoints[0]||origin} destination={persisted?.waypoints.at(-1)||destination} routes={routeLayers} selectionMode={selection} onMapSelect={point=>{if(selection==='ORIGIN')setOrigin(point);if(selection==='DESTINATION')setDestination(point);setSelection(undefined);}} fitKey={displayed?`route:${displayed.route_id}`:`route-input:${origin.latitude}:${origin.longitude}:${destination.latitude}:${destination.longitude}`}/>{persisted&&<div className="map-layer-note immutable"><span><i className="layer-dot route"/>Persisted command geometry</span><span>Never recalculated here</span></div>}</div></div>}
    {requestError ? <RouteErrorCard error={requestError}/> : null} {comparison&&<section className="panel policy-comparison"><div className="panel-title"><h2>Policy comparison</h2><span>Two independent route requests</span></div><div className="comparison-grid"><span/><strong>Shortest</strong><strong>Fastest</strong><span>Distance</span><button onClick={()=>setVisible('SHORTEST')}>{(comparison.shortest.distance_meters/1000).toFixed(2)} km</button><button onClick={()=>setVisible('FASTEST')}>{(comparison.fastest.distance_meters/1000).toFixed(2)} km</button><span>Expanded nodes</span><b>{comparison.shortest.expanded_nodes.toLocaleString()}</b><b>{comparison.fastest.expanded_nodes.toLocaleString()}</b><span>Snapshot</span><b>{comparison.shortest.snapshot_version}</b><b>{comparison.fastest.snapshot_version}</b></div></section>}{displayed&&<section className="panel"><RouteSummary route={displayed} persisted={Boolean(persisted)}/></section>}
    {!persisted&&!displayed&&!requestError&&<div className="route-empty"><RouteIcon/><div><strong>No route calculated</strong><span>Choose valid road-vehicle coordinates and a policy. Polaris never draws a fabricated fallback route.</span></div></div>}
  </div>;
}
