import { ArrowLeft, Clock3, RotateCcw, ShieldAlert, StopCircle } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useState } from 'react';
import { ConfirmationDialog } from '../components/operations/ConfirmationDialog';
import { EntityLink } from '../components/operations/EntityLink';
import { TaskLifecycleTimeline } from '../components/operations/LifecycleTimeline';
import { CommandStatusBadge, TaskPriorityBadge, TaskStatusBadge } from '../components/operations/OperationsStatus';
import { TaskRequirementsView, TaskTargetViewer, TaskTimingDiagnostics } from '../components/operations/TaskDetails';
import { BatteryIndicator, ConnectivityBadge, DeviceTypeIcon, LifecycleBadge } from '../components/status/Status';
import { ErrorState, PageLoader } from '../components/ui/States';
import { useAuth } from '../features/auth/AuthContext';
import { useProjects, useTwin } from '../features/fleet/queries';
import { canCancelTaskState, canRetryTaskState } from '../features/operations/model';
import { useTask } from '../features/operations/queries';
import { readableError } from '../lib/api/errors';
import { deviceTypeLabel, exactTime } from '../lib/format';
import { can } from '../lib/permissions';
import { useQueryClient } from '../lib/query/queryClient';

export default function TaskDetail() {
  const { taskId='' }=useParams(); const [params]=useSearchParams(); const {session,api}=useAuth(); const queryClient=useQueryClient();
  const detail=useTask(taskId); const projects=useProjects();
  const [action,setAction]=useState<'cancel'|'retry'|null>(null); const [working,setWorking]=useState(false); const [actionError,setActionError]=useState<unknown>();
  const task=detail.data?.task; const twin=useTwin(task?.assigned_device_id||'');
  if(detail.isLoading)return <PageLoader label="Loading task"/>; if(detail.error||!task)return <ErrorState error={detail.error||new Error('Task was not found.')} retry={()=>void detail.refetch()}/>;
  const latestCommand=[...(detail.data?.commands||[])].sort((a,b)=>b.sequence_number-a.sequence_number)[0];
  const cancellable=canCancelTaskState(task.status,latestCommand?.status); const retryable=canRetryTaskState(task.status); const back=`/tasks${params.get('return')?`?${params.get('return')}`:''}`;
  const mutate=async()=>{if(!api||!action)return;setWorking(true);setActionError(undefined);try{if(action==='cancel')await api.cancelTask(taskId);else await api.retryTask(taskId,300);setAction(null);queryClient.refresh(['task',session!.tenantId,taskId]);queryClient.refresh(['tasks',session!.tenantId]);queryClient.refresh(['commands',session!.tenantId]);}catch(error){setActionError(error);}finally{setWorking(false);}};
  const error=actionError?readableError(actionError):null;
  return <div className="page-stack operation-detail"><Link className="back-link" to={back}><ArrowLeft/> Back to tasks</Link><header className="operation-hero"><div><p className="eyebrow">Operator intent</p><h1>{task.task_type}</h1><code>{task.task_id}</code></div><div className="hero-badges"><TaskPriorityBadge priority={task.priority}/><TaskStatusBadge status={task.status}/></div><div className="operation-actions">{session&&can(session.role,'cancelTask')&&<button className="button secondary" disabled={!cancellable} title={!cancellable?'Cancellation is legal only before command delivery.':undefined} onClick={()=>setAction('cancel')}><StopCircle/> Cancel task</button>}{session&&can(session.role,'retryTask')&&<button className="button secondary" disabled={!retryable} title={!retryable?'Administrative task retry is legal only for failed or expired tasks.':undefined} onClick={()=>setAction('retry')}><RotateCcw/> Retry orchestration</button>}</div></header>
    {error&&<div className="inline-error"><strong>{error.status===409?'The task state changed or no longer permits this operation.':error.code||'Operation failed'}</strong><span>{error.status===409?'Refresh the task and review its current lifecycle.':error.message}</span>{error.requestId&&<small>Request ID: {error.requestId}</small>}</div>}
    {task.status==='PENDING'&&<div className="pending-callout"><Clock3/><div><strong>Waiting for an eligible device</strong><span>The task is durable. Polaris reconciliation can reconsider it while it remains pending and unexpired.</span></div></div>}
    <div className="operation-detail-grid"><section className="panel"><div className="panel-title"><h2>Task lifecycle</h2><span>Confirmed durable state</span></div><TaskLifecycleTimeline task={task}/>{task.failure_reason&&<div className="failure-reason"><ShieldAlert/><span><small>Failure reason</small><strong>{task.failure_reason}</strong></span></div>}</section><section className="panel"><div className="panel-title"><h2>Task metadata</h2><span>Version {task.version}</span></div><dl className="operation-metadata"><div><dt>Project</dt><dd>{projects.data?.find(project=>project.project_id===task.project_id)?.name||task.project_id||'Any project'}</dd></div><div><dt>Created by</dt><dd><code>{task.created_by}</code></dd></div><div><dt>Created</dt><dd>{exactTime(task.created_at)}</dd></div><div><dt>Expires</dt><dd>{exactTime(task.expires_at)}</dd></div><div><dt>Planning mode</dt><dd>{task.requirements.planning_mode||'Generic planner'}</dd></div><div><dt>Correlation ID</dt><dd><code>{task.correlation_id}</code></dd></div></dl></section></div>
    <div className="operation-detail-grid"><section className="panel"><div className="panel-title"><h2>Requirements</h2><span>Backend-authoritative eligibility</span></div><TaskRequirementsView taskType={task.task_type} requirements={task.requirements}/></section><section className="panel"><div className="panel-title"><h2>Target</h2><span>Immutable task document</span></div><TaskTargetViewer target={task.target}/></section></div>
    {task.assigned_device_id&&<section className="panel"><div className="panel-title"><h2>Exclusive assignment</h2><span>Current task assignment</span></div>{twin.data?<div className="assigned-device"><span className="large-device-icon"><DeviceTypeIcon type={twin.data.device.device_type_id}/></span><div><strong>{twin.data.device.display_name}</strong><small>{deviceTypeLabel(twin.data.device.device_type_id)} · {twin.data.device_id}</small></div><LifecycleBadge status={twin.data.device.lifecycle_status}/><ConnectivityBadge status={twin.data.connectivity.status}/><BatteryIndicator value={twin.data.reported_state?.energy_percent}/><Link className="button secondary" to={`/devices/${twin.data.device_id}`}>Open device</Link></div>:<EntityLink label="Assigned device" id={task.assigned_device_id} to={`/devices/${task.assigned_device_id}`}/>}</section>}
    <section className="panel"><div className="panel-title"><h2>Commands created for this task</h2><span>{detail.data?.commands.length||0} returned</span></div>{detail.data?.commands.length?<div className="related-commands">{detail.data.commands.map(command=><Link key={command.command_id} to={`/commands/${command.command_id}`}><span><strong>{command.command_type}</strong><code>{command.command_id}</code></span><span>Sequence {command.sequence_number}</span><CommandStatusBadge status={command.status}/></Link>)}</div>:<div className="compact-empty"><Clock3/><span>No command exists yet. The task remains operator intent until assignment succeeds.</span></div>}</section>
    <section className="panel"><div className="panel-title"><h2>Orchestration timing</h2><span>Creation response only</span></div><TaskTimingDiagnostics/></section>
    <ConfirmationDialog open={action==='cancel'} title="Cancel task?" confirmLabel="Cancel pending work" danger working={working} onClose={()=>!working&&setAction(null)} onConfirm={()=>void mutate()}><p>This is safe only before physical command delivery. If a command has already been delivered, Polaris rejects cancellation instead of pretending the device stopped.</p><p>If a physical device must stop after delivery, create an appropriate domain STOP task.</p></ConfirmationDialog>
    <ConfirmationDialog open={action==='retry'} title="Retry task orchestration?" confirmLabel="Make a new orchestration decision" working={working} onClose={()=>!working&&setAction(null)} onConfirm={()=>void mutate()}><p>This re-enters the same task into orchestration, extends its expiry, clears prior assignment state, and may select a device and create a new command.</p><p>It is different from retrying delivery of an existing immutable command.</p></ConfirmationDialog>
  </div>;
}
